kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-operator-in-istio-system
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: jaeger-operator
    namespace: default
roleRef:
  kind: Role
  name: jaeger-operator
  apiGroup: rbac.authorization.k8s.io
