kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-operator-in-online-boutique
  namespace: online-boutique
subjects:
  - kind: ServiceAccount
    name: jaeger-operator
    namespace: default
roleRef:
  kind: Role
  name: jaeger-operator
  apiGroup: rbac.authorization.k8s.io
